### PR TITLE
Use GitHub Actions to build NGCHM artifacts

### PR DESCRIPTION
**Pull request by marohrdanz**
This pull request uses GitHub Actions to build the needed artifacts from the [NGCHM Viewer](https://github.com/MD-Anderson-Bioinformatics/NG-CHM) project. 

The GitHub Actions workflow does the following:

- Checks out specified tag from [NGCHM Viewer](https://github.com/MD-Anderson-Bioinformatics/NG-CHM)
- Builds ShaidyMapGen.jar for java 8 from build_shaidyRmapgen.xml
- Builds ngchmWidget-min.js from build_ngchmApp.xml
- Updates the DESCRIPTION Version number to the NGCHM Viewer tag
- Verifies the resulting package builds
- Commits these changes back to this repo

The final commit is only made if all of the previous steps are successful, and an email is sent if the job fails.

With this GitHub Action workflow, updating these files is no longer a tedious manual process, but is instead a matter of updating the NGCHM_TAG environment variable in .github/workflows/build-artifacts-from-ngchm.yml, and pushing that change to this repo.

### CODE REVIEW

**Comment by ChrisWakefield** [comment]
Is this adding/updating ShaidyMapGen.jar and ngchmWidget-min.js even though the purpose is to create the action to rebuild them?  It seems like those files would be removed instead?

Can you (should we?) just use the Dockerfile to build these things?  Then we would not have multiple places to configure which java and which ant to use, etc.

**Review by ChrisWakefield — APPROVED** [review]
We discussed my comments, and decided to approve this as is.

**Comment by marohrdanz** [comment]
Converting this to a DRAFT because I plan to quickly supersede this PR by a PR in the NGCHM Viewer project to accomplish this same task.

**Comment by marohrdanz** [comment]
As suggested above, instead of the pull request, I made one for the NGCHM Viewer project, and it was merged in some time ago: https://github.com/MD-Anderson-Bioinformatics/NG-CHM/pull/124

**Pull request closed without merging**
